// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:全局user_id" json:"id"` // 全局user_id
	NickName   string    `gorm:"column:nick_name;not null" json:"nick_name"`
	Sex        int32     `gorm:"column:sex;not null;comment:默认0 其他， 1：男 2：女" json:"sex"`                                // 默认0 其他， 1：男 2：女
	Password   string    `gorm:"column:password;not null;comment:64长度，全局唯一一个密码，不支持昵称登录，支持微信登录和手机号密码登录" json:"password"` // 64长度，全局唯一一个密码，不支持昵称登录，支持微信登录和手机号密码登录
	Status     int32     `gorm:"column:status;not null;default:1;comment:默认1：正常  -1：禁用" json:"status"`                  // 默认1：正常  -1：禁用
	MobileBind int32     `gorm:"column:mobile_bind;not null;comment:默认0：未绑定 1：已绑定" json:"mobile_bind"`                  // 默认0：未绑定 1：已绑定
	WechatBind int32     `gorm:"column:wechat_bind;not null;comment:默认0：未绑定 1：已绑定" json:"wechat_bind"`                  // 默认0：未绑定 1：已绑定
	IconKey    string    `gorm:"column:icon_key;not null;comment:长度固定32，云存储key uuid去 -" json:"icon_key"`                // 长度固定32，云存储key uuid去 -
	CreateAt   time.Time `gorm:"column:create_at;not null" json:"create_at"`
	UpdateAt   time.Time `gorm:"column:update_at;not null" json:"update_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
