// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserProfile = "user_profile"

// UserProfile mapped from table <user_profile>
type UserProfile struct {
	ID             int64     `gorm:"column:id;primaryKey;comment:自增（无实际用途）" json:"id"`                               // 自增（无实际用途）
	UserID         int64     `gorm:"column:user_id;not null;comment:全局用户id" json:"user_id"`                          // 全局用户id
	StudentNo      string    `gorm:"column:student_no;not null;comment:学号" json:"student_no"`                        // 学号
	SchoolSystemID int64     `gorm:"column:school_system_id;not null;comment:系统内的学校ID" json:"school_system_id"`      // 系统内的学校ID
	GradeEnum      int32     `gorm:"column:grade_enum;not null;default:12;comment:1--12分别为一年级到高三" json:"grade_enum"` // 1--12分别为一年级到高三
	ClassName      string    `gorm:"column:class_name;not null;comment:班级名称" json:"class_name"`                      // 班级名称
	UpdateAt       time.Time `gorm:"column:update_at;not null" json:"update_at"`
	CreateAt       time.Time `gorm:"column:create_at;not null" json:"create_at"`
}

// TableName UserProfile's table name
func (*UserProfile) TableName() string {
	return TableNameUserProfile
}
