// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.25.3
// source: latex.proto

package latexOcr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求消息，包含要识别的图片数据
type LatexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"` // 修改为 bytes 类型来存储图片数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatexRequest) Reset() {
	*x = LatexRequest{}
	mi := &file_latex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatexRequest) ProtoMessage() {}

func (x *LatexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_latex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatexRequest.ProtoReflect.Descriptor instead.
func (*LatexRequest) Descriptor() ([]byte, []int) {
	return file_latex_proto_rawDescGZIP(), []int{0}
}

func (x *LatexRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

// 响应消息，包含识别结果
type LatexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatexResponse) Reset() {
	*x = LatexResponse{}
	mi := &file_latex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatexResponse) ProtoMessage() {}

func (x *LatexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_latex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatexResponse.ProtoReflect.Descriptor instead.
func (*LatexResponse) Descriptor() ([]byte, []int) {
	return file_latex_proto_rawDescGZIP(), []int{1}
}

func (x *LatexResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_latex_proto protoreflect.FileDescriptor

var file_latex_proto_rawDesc = string([]byte{
	0x0a, 0x0b, 0x6c, 0x61, 0x74, 0x65, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6c,
	0x61, 0x74, 0x65, 0x78, 0x4f, 0x63, 0x72, 0x22, 0x2d, 0x0a, 0x0c, 0x4c, 0x61, 0x74, 0x65, 0x78,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x27, 0x0a, 0x0d, 0x4c, 0x61, 0x74, 0x65, 0x78, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32,
	0x51, 0x0a, 0x0c, 0x4c, 0x61, 0x74, 0x65, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x41, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x7a, 0x65, 0x4c, 0x61, 0x74, 0x65,
	0x78, 0x12, 0x16, 0x2e, 0x6c, 0x61, 0x74, 0x65, 0x78, 0x4f, 0x63, 0x72, 0x2e, 0x4c, 0x61, 0x74,
	0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6c, 0x61, 0x74, 0x65,
	0x78, 0x4f, 0x63, 0x72, 0x2e, 0x4c, 0x61, 0x74, 0x65, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x61, 0x74, 0x65,
	0x78, 0x4f, 0x63, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_latex_proto_rawDescOnce sync.Once
	file_latex_proto_rawDescData []byte
)

func file_latex_proto_rawDescGZIP() []byte {
	file_latex_proto_rawDescOnce.Do(func() {
		file_latex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_latex_proto_rawDesc), len(file_latex_proto_rawDesc)))
	})
	return file_latex_proto_rawDescData
}

var file_latex_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_latex_proto_goTypes = []any{
	(*LatexRequest)(nil),  // 0: latexOcr.LatexRequest
	(*LatexResponse)(nil), // 1: latexOcr.LatexResponse
}
var file_latex_proto_depIdxs = []int32{
	0, // 0: latexOcr.LatexService.RecognizeLatex:input_type -> latexOcr.LatexRequest
	1, // 1: latexOcr.LatexService.RecognizeLatex:output_type -> latexOcr.LatexResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_latex_proto_init() }
func file_latex_proto_init() {
	if File_latex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_latex_proto_rawDesc), len(file_latex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_latex_proto_goTypes,
		DependencyIndexes: file_latex_proto_depIdxs,
		MessageInfos:      file_latex_proto_msgTypes,
	}.Build()
	File_latex_proto = out.File
	file_latex_proto_goTypes = nil
	file_latex_proto_depIdxs = nil
}
