# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: latex.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'latex.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blatex.proto\x12\x08latexOcr\"\"\n\x0cLatexRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"\x1f\n\rLatexResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2Q\n\x0cLatexService\x12\x41\n\x0eRecognizeLatex\x12\x16.latexOcr.LatexRequest\x1a\x17.latexOcr.LatexResponseB\x10Z\x0eproto/latexOcrb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'latex_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\016proto/latexOcr'
  _globals['_LATEXREQUEST']._serialized_start=25
  _globals['_LATEXREQUEST']._serialized_end=59
  _globals['_LATEXRESPONSE']._serialized_start=61
  _globals['_LATEXRESPONSE']._serialized_end=92
  _globals['_LATEXSERVICE']._serialized_start=94
  _globals['_LATEXSERVICE']._serialized_end=175
# @@protoc_insertion_point(module_scope)
