// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: latex.proto

package latexOcr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LatexService_RecognizeLatex_FullMethodName = "/basic.LatexService/RecognizeLatex"
)

// LatexServiceClient is the client API for LatexService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义服务
type LatexServiceClient interface {
	// 定义一个方法，用于LaTeX图片识别
	RecognizeLatex(ctx context.Context, in *LatexRequest, opts ...grpc.CallOption) (*LatexResponse, error)
}

type latexServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLatexServiceClient(cc grpc.ClientConnInterface) LatexServiceClient {
	return &latexServiceClient{cc}
}

func (c *latexServiceClient) RecognizeLatex(ctx context.Context, in *LatexRequest, opts ...grpc.CallOption) (*LatexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LatexResponse)
	err := c.cc.Invoke(ctx, LatexService_RecognizeLatex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LatexServiceServer is the server API for LatexService service.
// All implementations must embed UnimplementedLatexServiceServer
// for forward compatibility.
//
// 定义服务
type LatexServiceServer interface {
	// 定义一个方法，用于LaTeX图片识别
	RecognizeLatex(context.Context, *LatexRequest) (*LatexResponse, error)
	mustEmbedUnimplementedLatexServiceServer()
}

// UnimplementedLatexServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLatexServiceServer struct{}

func (UnimplementedLatexServiceServer) RecognizeLatex(context.Context, *LatexRequest) (*LatexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecognizeLatex not implemented")
}
func (UnimplementedLatexServiceServer) mustEmbedUnimplementedLatexServiceServer() {}
func (UnimplementedLatexServiceServer) testEmbeddedByValue()                      {}

// UnsafeLatexServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LatexServiceServer will
// result in compilation errors.
type UnsafeLatexServiceServer interface {
	mustEmbedUnimplementedLatexServiceServer()
}

func RegisterLatexServiceServer(s grpc.ServiceRegistrar, srv LatexServiceServer) {
	// If the following call pancis, it indicates UnimplementedLatexServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LatexService_ServiceDesc, srv)
}

func _LatexService_RecognizeLatex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LatexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LatexServiceServer).RecognizeLatex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LatexService_RecognizeLatex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LatexServiceServer).RecognizeLatex(ctx, req.(*LatexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LatexService_ServiceDesc is the grpc.ServiceDesc for LatexService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LatexService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "basic.LatexService",
	HandlerType: (*LatexServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecognizeLatex",
			Handler:    _LatexService_RecognizeLatex_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "latex.proto",
}
